---
collections:
  - name: infra.aap_configuration
  - name: ansible.controller
  - name: kubevirt.core
  - name: kubernetes.core
  - name: community.crypto
  - name: redhat.rhel_system_roles
  - name: ansible.eda

roles: []
